
/* File generated by gen_cfile.py. Should not be modified. */

#include "od.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS16 speed = 0x0;		/* Mapped at index 0x2000, subindex 0x00 */
UNS16 volt = 0x0;		/* Mapped at index 0x2001, subindex 0x00 */
UNS16 curr = 0x0;		/* Mapped at index 0x2002, subindex 0x00 */
UNS8 temp = 0x0;		/* Mapped at index 0x2003, subindex 0x00 */
UNS16 rpm = 0x0;		/* Mapped at index 0x2004, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 esc_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 esc_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 esc_iam_a_slave = 1;

TIMER_HANDLE esc_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 esc_obj1000 = 0x0;	/* 0 */
                    subindex esc_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&esc_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 esc_obj1001 = 0x0;	/* 0 */
                    subindex esc_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&esc_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 esc_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 esc_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t esc_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex esc_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&esc_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&esc_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 esc_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 esc_obj1006 = 0x0;   /* 0 */

/* index 0x1008 :   Manufacturer Device Name. */
                    UNS8 esc_obj1008[10] = "ESC";
                    subindex esc_Index1008[] = 
                     {
                       { RO, visible_string, 10, (void*)&esc_obj1008 }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 esc_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 esc_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 esc_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 esc_highestSubIndex_obj1016 = 0;
                    UNS32 esc_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 esc_obj1017 = 5000;	/* 0 */
                    ODCallback_t esc_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex esc_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&esc_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 esc_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 esc_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 esc_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 esc_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 esc_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex esc_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&esc_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&esc_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&esc_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&esc_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&esc_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 esc_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 esc_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 esc_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex esc_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&esc_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&esc_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&esc_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 esc_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 esc_obj1400_COB_ID_used_by_PDO = 0x27F;	/* 639 */
                    UNS8 esc_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 esc_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 esc_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 esc_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 esc_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t esc_Index1400_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex esc_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&esc_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&esc_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&esc_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&esc_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&esc_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&esc_obj1400_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&esc_obj1400_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 esc_highestSubIndex_obj1600 = 1; /* number of subindex - 1*/
                    UNS32 esc_obj1600[] = 
                    {
                      0x20000010	/* 536870928 */
                    };
                    ODCallback_t esc_Index1600_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex esc_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&esc_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&esc_obj1600[0] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 esc_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 esc_obj1800_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 esc_obj1800_Transmission_Type = 0x0;	/* 0 */
                    UNS16 esc_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 esc_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 esc_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 esc_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t esc_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex esc_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&esc_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&esc_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&esc_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&esc_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&esc_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&esc_obj1800_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&esc_obj1800_SYNC_start_value }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 esc_highestSubIndex_obj1A00 = 4; /* number of subindex - 1*/
                    UNS32 esc_obj1A00[] = 
                    {
                      0x20010010,	/* 536936464 */
                      0x20020010,	/* 537002000 */
                      0x20030008,	/* 537067528 */
                      0x20040010	/* 537133072 */
                    };
                    ODCallback_t esc_Index1A00_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex esc_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&esc_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&esc_obj1A00[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&esc_obj1A00[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&esc_obj1A00[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&esc_obj1A00[3] }
                     };

/* index 0x2000 :   Mapped variable speed */
                    ODCallback_t speed_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex esc_Index2000[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&speed }
                     };

/* index 0x2001 :   Mapped variable volt */
                    subindex esc_Index2001[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&volt }
                     };

/* index 0x2002 :   Mapped variable curr */
                    subindex esc_Index2002[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&curr }
                     };

/* index 0x2003 :   Mapped variable temp */
                    subindex esc_Index2003[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&temp }
                     };

/* index 0x2004 :   Mapped variable rpm */
                    subindex esc_Index2004[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&rpm }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable esc_objdict[] = 
{
  { (subindex*)esc_Index1000,sizeof(esc_Index1000)/sizeof(esc_Index1000[0]), 0x1000},
  { (subindex*)esc_Index1001,sizeof(esc_Index1001)/sizeof(esc_Index1001[0]), 0x1001},
  { (subindex*)esc_Index1008,sizeof(esc_Index1008)/sizeof(esc_Index1008[0]), 0x1008},
  { (subindex*)esc_Index1017,sizeof(esc_Index1017)/sizeof(esc_Index1017[0]), 0x1017},
  { (subindex*)esc_Index1018,sizeof(esc_Index1018)/sizeof(esc_Index1018[0]), 0x1018},
  { (subindex*)esc_Index1200,sizeof(esc_Index1200)/sizeof(esc_Index1200[0]), 0x1200},
  { (subindex*)esc_Index1400,sizeof(esc_Index1400)/sizeof(esc_Index1400[0]), 0x1400},
  { (subindex*)esc_Index1600,sizeof(esc_Index1600)/sizeof(esc_Index1600[0]), 0x1600},
  { (subindex*)esc_Index1800,sizeof(esc_Index1800)/sizeof(esc_Index1800[0]), 0x1800},
  { (subindex*)esc_Index1A00,sizeof(esc_Index1A00)/sizeof(esc_Index1A00[0]), 0x1A00},
  { (subindex*)esc_Index2000,sizeof(esc_Index2000)/sizeof(esc_Index2000[0]), 0x2000},
  { (subindex*)esc_Index2001,sizeof(esc_Index2001)/sizeof(esc_Index2001[0]), 0x2001},
  { (subindex*)esc_Index2002,sizeof(esc_Index2002)/sizeof(esc_Index2002[0]), 0x2002},
  { (subindex*)esc_Index2003,sizeof(esc_Index2003)/sizeof(esc_Index2003[0]), 0x2003},
  { (subindex*)esc_Index2004,sizeof(esc_Index2004)/sizeof(esc_Index2004[0]), 0x2004},
};

const indextable * esc_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1008: i = 2;break;
		case 0x1017: i = 3;*callbacks = esc_Index1017_callbacks; break;
		case 0x1018: i = 4;break;
		case 0x1200: i = 5;break;
		case 0x1400: i = 6;*callbacks = esc_Index1400_callbacks; break;
		case 0x1600: i = 7;*callbacks = esc_Index1600_callbacks; break;
		case 0x1800: i = 8;*callbacks = esc_Index1800_callbacks; break;
		case 0x1A00: i = 9;*callbacks = esc_Index1A00_callbacks; break;
		case 0x2000: i = 10;*callbacks = speed_callbacks; break;
		case 0x2001: i = 11;break;
		case 0x2002: i = 12;break;
		case 0x2003: i = 13;break;
		case 0x2004: i = 14;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &esc_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status esc_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index esc_firstIndex = {
  5, /* SDO_SVR */
  0, /* SDO_CLT */
  6, /* PDO_RCV */
  7, /* PDO_RCV_MAP */
  8, /* PDO_TRS */
  9 /* PDO_TRS_MAP */
};

const quick_index esc_lastIndex = {
  5, /* SDO_SVR */
  0, /* SDO_CLT */
  6, /* PDO_RCV */
  7, /* PDO_RCV_MAP */
  8, /* PDO_TRS */
  9 /* PDO_TRS_MAP */
};

const UNS16 esc_ObjdictSize = sizeof(esc_objdict)/sizeof(esc_objdict[0]); 

CO_Data esc_Data = CANOPEN_NODE_DATA_INITIALIZER(esc);

