
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef ESC_H
#define ESC_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 esc_valueRangeTest (UNS8 typeValue, void * value);
const indextable * esc_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data esc_Data;
extern UNS16 speed;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS16 volt;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS16 curr;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS8 temp;		/* Mapped at index 0x2003, subindex 0x00*/
extern UNS16 rpm;		/* Mapped at index 0x2004, subindex 0x00*/

#endif // ESC_H
