
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef OD_H
#define OD_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 F4BY_valueRangeTest (UNS8 typeValue, void * value);
const indextable * F4BY_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data F4BY_Data;
extern UNS16 speed[4];		/* Mapped at index 0x2000, subindex 0x01 - 0x04 */
extern UNS16 voltage[8];		/* Mapped at index 0x2001, subindex 0x01 - 0x08 */
extern UNS16 current[8];		/* Mapped at index 0x2002, subindex 0x01 - 0x08 */
extern UNS8 temperature[8];		/* Mapped at index 0x2003, subindex 0x01 - 0x08 */
extern UNS16 rpm[8];		/* Mapped at index 0x2004, subindex 0x01 - 0x08 */

#endif // OD_H
